apiVersion: apps/v1
kind: Deployment
metadata:
  name: lando
  labels:
    app: lando
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lando
  template:
    metadata:
      labels:
        app: lando
    spec:
      containers:
        - name: lando
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
